---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: pizza
spec:
  hostname: "pizza.lcl"
  prefix: /
  service: pizza
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: sushi
spec:
  hostname: "*"
  prefix: /sushi/
  service: sushi
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: pasta
spec:
  hostname: "*"
  prefix: /
  service: pasta