---
{{- range $i, $_ := until (int (sub .Values.hostCount 1)) }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: minio-{{ add $i 1}}
spec:
  hostname: "minio-{{add $i 1}}.lcl:8080"
  prefix: /
  service: minio-{{add $i 1}}:8080
---
{{- end }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: minio-0
spec:
  hostname: "*"
  prefix: /
  service: minio-0:8080