apiVersion: v1
kind: ConfigMap
metadata:
  name: bucket-list
  namespace: emissary
data:
  buckets.txt: |
    bucket1
    bucket2
    bucket3
    bucket4
    bucket5
    bucket6
    bucket7
    bucket8
    bucket9
    bucket10
    bucket11
    bucket12
    bucket13
    bucket14
    bucket15
    bucket16
    bucket17
    bucket18
    bucket19
    bucket20
    bucket21
    bucket22
    bucket23
    bucket24
    bucket25
    bucket26
    bucket27
    bucket28
    bucket29
    bucket30
    bucket31
    bucket32
    bucket33
    bucket34
    bucket35
    bucket36
    bucket37
    bucket38
    bucket39
    bucket40
    bucket41
    bucket42
    bucket43
    bucket44
    bucket45
    bucket46
    bucket47
    bucket48
    bucket49
    bucket50
    bucket51
    bucket52
    bucket53
    bucket54
    bucket55
    bucket56
    bucket57
    bucket58
    bucket59
    bucket60
    bucket61
    bucket62
    bucket63
    bucket64
    bucket65
    bucket66
    bucket67
    bucket68
    bucket69
    bucket70
    bucket71
    bucket72
    bucket73
    bucket74
    bucket75
    bucket76
    bucket77
    bucket78
    bucket79
    bucket80
    bucket81
    bucket82
    bucket83
    bucket84
    bucket85
    bucket86
    bucket87
    bucket88
    bucket89
    bucket90
    bucket91
    bucket92
    bucket93
    bucket94
    bucket95
    bucket96
    bucket97
    bucket98
    bucket99
    bucket100