{{- range .Values.mappings }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: "mapping-{{ .host }}"
spec:
  host: "{{ .host }}"
  prefix: "/"
  service: "{{ .service }}"
---
{{- end }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: pasta
spec:
  hostname: "*"
  prefix: /
  service: pasta