mappings:
  - host: host1.lcl
    service: pizza
  - host: host2.lcl
    service: sushi
  - host: host3.lcl
    service: pizza
  - host: host4.lcl
    service: sushi
  - host: host5.lcl
    service: pizza
  - host: host6.lcl
    service: sushi
  - host: host7.lcl
    service: pizza
  - host: host8.lcl
    service: sushi